In [1]:
import torch

In [2]:
x = torch.linspace(1, 27, steps=27).view(9, 3)
bbb = torch.where(x > 5, torch.full_like(x, 5), x)

In [6]:
bb=torch.where(x>5,torch.Tensor([5]),x)

In [8]:
print(x)
#print('\t')
print(bbb)
print('\n')
print(bb)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]])
tensor([[1., 2., 3.],
        [4., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


tensor([[1., 2., 3.],
        [4., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


In [ ]:
N = int(input())
while N != 0:
    grades = [int(grade) for grade in input().split()]
    target = int(input())
    print(grades.count(target))
    N = int(input())

1
40
40
1
4
10 40 70 80
70
1
3
20 90 50
20
1
