In [1]:
import torch
import numpy as np
import torch.nn as nn

print(torch.__version__)

1.4.0+cpu


In [6]:
x=torch.rand(4,2,3)
l=nn.Linear(3,2)
x1=torch.rand(4,2,3)

In [7]:
print(x,'\n',x1)

tensor([[[0.2309, 0.1385, 0.9924],
         [0.1047, 0.9431, 0.7202]],

        [[0.7513, 0.4351, 0.9169],
         [0.5523, 0.7519, 0.8743]],

        [[0.9072, 0.3436, 0.5456],
         [0.1348, 0.1630, 0.9092]],

        [[0.8118, 0.4208, 0.0097],
         [0.9176, 0.9385, 0.5855]]]) 
 tensor([[[0.8362, 0.1368, 0.5079],
         [0.3379, 0.5915, 0.7950]],

        [[0.7383, 0.3452, 0.7040],
         [0.0712, 0.4878, 0.4032]],

        [[0.1832, 0.9753, 0.3479],
         [0.8639, 0.7241, 0.9558]],

        [[0.5863, 0.2502, 0.8930],
         [0.7758, 0.0168, 0.3660]]])


In [8]:
n=x*x1
n1=torch.mul(x,x1)
print(n,'\n',n1)

tensor([[[0.1931, 0.0189, 0.5041],
         [0.0354, 0.5578, 0.5726]],

        [[0.5547, 0.1502, 0.6456],
         [0.0393, 0.3668, 0.3525]],

        [[0.1662, 0.3351, 0.1898],
         [0.1165, 0.1180, 0.8690]],

        [[0.4759, 0.1053, 0.0087],
         [0.7119, 0.0158, 0.2143]]]) 
 tensor([[[0.1931, 0.0189, 0.5041],
         [0.0354, 0.5578, 0.5726]],

        [[0.5547, 0.1502, 0.6456],
         [0.0393, 0.3668, 0.3525]],

        [[0.1662, 0.3351, 0.1898],
         [0.1165, 0.1180, 0.8690]],

        [[0.4759, 0.1053, 0.0087],
         [0.7119, 0.0158, 0.2143]]])


In [9]:
torch.sum(n1,)

tensor(7.3175)

In [18]:
m=torch.ones(2,3,4)
m

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [20]:
torch.sum(m.sum(2),1)

tensor([12., 12.])